### ISSUE TITLE
base_url

### ISSUE THREAD

**Issue by comeback01** [Shubhamsaboo/awesome-llm-apps#1]
Hello,

I would like to know how to change the base URL. The idea is to be able to use OpenRouter, which is compatible with OpenAI, and they offer free models.

Thank you very much!

**Comment by Shubhamsaboo** [comment]
Can you please elaborate on this? 

Which example exactly you are referring to?

**Comment by comeback01** [comment]
There are suppliers that offer APIs that are 100% compatible with OpenAI, such as:

- https://www.together.ai/
- https://fireworks.ai/
- https://openrouter.ai

I particularly like https://openrouter.ai because it provides models like Claude 4, GPT-4, Meta: Llama 3 70B Instruct, etc.

This provider also offers completely free models, such as Mistral 7B Instruct.

To use these models, there is no need to modify the code. However, you need to specify:
- an API key (api_key)
- the chosen model (model)

As in your program, you must also provide a base URL (baseURL), which could be:

- https://openrouter.ai/api/v1
- https://api.together.xyz/v1

I hope this makes things clearer.

Thank you for your help.

**Comment by Shubhamsaboo** [comment]
Gotcha. 

Embedchain supports the use of following LLM and support the providers listed here: https://docs.embedchain.ai/components/llms

All you need to do is to change the config of your embedchain app. You can find the instructions on how to use them on the above link. 

I hope this solves your problem.

**Comment by Shubhamsaboo** [comment]
Closing this as there is no response for a while.

**Comment by biometricdiwan-web** [comment]
readme-2026-refresh
