### ISSUE TITLE
GitGuardian

### ISSUE THREAD

**Issue by alonsoir** [Shubhamsaboo/awesome-llm-apps#18]
Hi, i think this is probably a false negative, but, GitGuardian show me in ai_journalist_agent/journalist_agent.py

instructions=[
            "Given a topic, first generate a list of 3 search terms related to that topic.",
            "For each search term, `search_google` and analyze the results."
            "From the results of all searcher, return the 10 most relevant URLs to the topic.",
            "Remember: you are writing for the New York Times, so the quality of the sources is important.",
        ],
        tools=[SerpApiTools(api_key="649ee0e7d64c6704b8ff92f3b01a424accfe6dbece128d043b17641b875e5f69")],
        add_datetime_to_instructions=True,

0f1be80

**Comment by Shubhamsaboo** [comment]
Yeah, committed it with the key by mistake. But now the access is revoked. Thank you.
