### ISSUE TITLE
AttributeError: module 'ollama' has no attribute 'chat'

### ISSUE THREAD

**Issue by shyamshyre** [Shubhamsaboo/awesome-llm-apps#2]
Error while executing the Program.

Inititally it was throwing if the model name is given as llama3. Then i changed with the modelname displaying in ollama:list.

Then it ran and displayed " Web Page Successfully Loaded". Then after made an attempt to chat then it was throwing below error.

module 'ollama' has no attribute 'chat'

**Comment by shyamshyre** [comment]
<img width="791" alt="Screenshot 2024-05-03 at 12 45 59 AM" src="https://github.com/Shubhamsaboo/awesome-llm-apps/assets/1207919/e24e4d4d-00f7-4012-a0d3-b36caae1da3b">

**Comment by shyamshyre** [comment]
Any help ? Any breakthrough??

**Comment by Shubhamsaboo** [comment]
What's the name of your python file? 

Is your file named ollama.py?

**Comment by Shubhamsaboo** [comment]
<img width="820" alt="Screenshot 2024-05-04 at 12 19 57 PM" src="https://github.com/Shubhamsaboo/awesome-llm-apps/assets/31396011/cc53f664-7903-4ef0-88a9-1f578a28b43a">

The same code works for me, make sure your file is not named as ollama.py and you install all the requirements correctly.

**Comment by shyamshyre** [comment]
Spot on ! Same Mistake.
Thanks, you made my day !!
