### ISSUE TITLE
Nice, but this code is buggy

### ISSUE THREAD

**Issue by josedandrade** [Shubhamsaboo/awesome-llm-apps#23]
`            config = {
                "vector_store": {
                    "provider": "qdrant",
                    "config": {
                        "host": "localhost",
                        "port": 6333,
                    }
                },
            }`

You had a model name here. It raises an error. There are other errors.

**Comment by Shubhamsaboo** [comment]
Can you also please link the file as well? 

All the code files are tested and then uploaded to this repo. Curious what's the errror?

**Comment by d4ndr4d3** [comment]
I ran the code AS IS and get this error:

```
Configuration validation error: 1 validation error for MemoryConfig
vector_store
  Value error, Extra fields not allowed: model. Please input only the following fields: path, embedding_model_dims, host, on_disk, collection_name, url, api_key, port, client [type=value_error, input_value={'model': 'gpt-4o-mini', ..., 'path': '/tmp/qdrant'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
2024-09-15 09:14:29.623 Uncaught app exception
Traceback (most recent call last):
  File "/home/dandrade/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/home/dandrade/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/home/dandrade/customersupport/storiginal.py", line 99, in <module>
    support_agent = CustomerSupportAIAgent()
  File "/home/dandrade/customersupport/storiginal.py", line 32, in __init__
    self.memory = Memory.from_config(config)
  File "/home/dandrade/.local/lib/python3.10/site-packages/mem0/memory/main.py", line 57, in from_config
    config = MemoryConfig(**config_dict)
  File "/home/dandrade/.local/lib/python3.10/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for MemoryConfig
vector_store
  Value error, Extra fields not allowed: model. Please input only the following fields: path, embedding_model_dims, host, on_disk, collection_name, url, api_key, port, client [type=value_error, input_value={'model': 'gpt-4o-mini', ..., 'path': '/tmp/qdrant'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
```

By removing model in config, and generating synthetic data, I get warnings of every datapoint generated: 

From
`
config = {
    "vector_store": {
        "provider": "qdrant",
        "config": {
            "model": "gpt-4o-mini",
            "host": "localhost",
            "port": 6333,
        }
    },
}
`

to this
`
config = {
    "vector_store": {
        "provider": "qdrant",
        "config": {
            "host": "localhost",
            "port": 6333,
        }
    },
}
`

DeprecationWarning: The current add API output format is deprecated. To use the latest format, set `api_version='v1.1'`. The current format will be removed in mem0ai 1.1.0 and later versions.

However:

Synthetic data generated successfully!

![image](https://github.com/user-attachments/assets/9ebe0bbb-bb17-4281-91fb-570c255547ed)

Now, I will try to view customer profile. It works, although not as verbose as your example in the video:

`{"customer_profile":{"customer_id":"Anna","name":"Anna Thompson","email":"anna.thompson@example.com","phone":"+1-555-0173","join_date":"2021-06-15","loyalty_level":"Gold","preferences":{"favorite_categories":["Laptops","Smartphones","Wearables"],"preferred_brands":["Apple","Samsung","Dell"],"shopping_frequency":"Monthly"},"shipping_address":{"address_line_1":"123 Tech Lane","address_line_2":"Apt 4B","city":"San Francisco","state":"CA","zip_code":"94107","country":"USA"}},"recent_order":{"order_number":"TG123456789","order_date":"2024-09-05","expected_delivery_date":"2024-09-17","product":{"name":"Apple MacBook Pro 16-inch","price":2499.99,"sku":"MBP16-1TB"}},"previous_orders":[{"order_number":"TG987654321","order_date":"2024-04-12","product":{"name":"Samsung Galaxy S23 Ultra","price":1199.99,"sku":"SGS23U-512GB"}},{"order_number":"TG543216789","order_date":"2023-11-30","product":{"name":"Dell XPS 13","price":1399.99,"sku":"DXPS13-256GB"}},{"order_number":"TG135792468","order_date":"2023-07-15","product":{"name":"Apple Watch Series 8","price":399.99,"sku":"AW8-45MM"}}],"customer_service_interactions":[{"interaction_id":"CS1001","date":"2024-04-15","issue":"Received a faulty Samsung Galaxy S23 Ultra.","resolution":"Replacement ordered and shipped within 48 hours."},{"interaction_id":"CS1002","date":"2023-12-25","issue":"Warranty inquiry for Dell XPS 13.","resolution":"Customer service provided warranty details and repair process."}],"shopping_behavior_patterns":{"spending_trend":"High-value electronics, prefers to purchase premium devices.","order frequency":"Regular shopper, approximately once a month.","brand loyalty":"Strong preference for premium brands, frequently reassessed through reviews."}}`
 
![image](https://github.com/user-attachments/assets/e4ceefee-6026-43af-afa5-e98500d978a7)

Now, I will try to get Memory Info. I get error

![image](https://github.com/user-attachments/assets/95aea6ec-1e98-4fd9-a9ee-8c4375967e9a)

`2024-09-15 09:26:43.520 Uncaught app exception
Traceback (most recent call last):
  File "/home/dandrade/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
  File "/home/dandrade/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/home/dandrade/customersupport/storiginal.py", line 132, in <module>
    st.sidebar.write(f"- {mem['text']}")
KeyError: 'text'`

This error prevents further interactions and conversations.

![image](https://github.com/user-attachments/assets/4645687f-5ed3-4965-9751-32ec79e355e4)

**Comment by d4ndr4d3** [comment]
I made it run, did some tweaking to the code.

**Comment by Tiath** [comment]
> I made it run, did some tweaking to the code.

How do I fix it?

**Comment by barnejs** [comment]
thx!
