### ISSUE TITLE
local_rag_agent/local_rag_agent.py

### ISSUE THREAD

**Issue by chiragvels** [Shubhamsaboo/awesome-llm-apps#31]
Hi,

In this requiremets should be updated so that openai should also be installed.
phi interanally using this.

I am getting error 

> Traceback (most recent call last):
>   File "/ai/awesome-llm-apps/rag_tutorials/local_rag_agent/local_rag_agent.py", line 5, in <module>
>     from phi.vectordb.qdrant import Qdrant
>   File "/ai/awesome-llm-apps/lib/python3.12/site-packages/phi/vectordb/qdrant/__init__.py", line 1, in <module>
>     from phi.vectordb.qdrant.qdrant import Qdrant
>   File "/ai/awesome-llm-apps/lib/python3.12/site-packages/phi/vectordb/qdrant/qdrant.py", line 14, in <module>
>     from phi.embedder.openai import OpenAIEmbedder
>   File "/ai/awesome-llm-apps/lib/python3.12/site-packages/phi/embedder/openai.py", line 11, in <module>
>     raise ImportError("`openai` not installed")
> ImportError: `openai` not installed

May be uvicorn and fastapi as well.

Thanks,

**Comment by chiragvels** [comment]
I am also getting this error.
WARNING  model "openhermes" not found, try pulling it first                                                                                                                                                 
ERROR    Error searching for documents: Unexpected Response: 400 (Bad Request)   

So Is that anything you can help?

Thanks

**Comment by ramonm21** [comment]
i also got the missing openai error first. installed that with pip install openai

then also got the "openhermes not found error" why would it try to use this? if the example is through llama3.2 then it should just run with llama3.2

localhost:7777 just says {"detail":"Not Found"}
localhost:6333 is running {"title":"qdrant - vector search engine","version":"1.12.3","commit":"7629faa6526aa866099b73d6c9b55aea47c2b54b"}

in the phidata.app Chat i can select the localhost:7777 endpoint and then the Local Agent RAG with llama3.2, but it doesnt have any knowledge (pdfs)

also get these errors:
WARNING  Failed to deepcopy field: knowledge - cannot pickle '_thread.RLock' object   
ERROR    Error searching for documents: Unexpected Response: 400 (Bad Request)                                                                                                                                               
         Raw response content:                                                                                                                                                                                               
         b'{"status":{"error":"Wrong input: Vector dimension error: expected dim: 4096, got 0"},"time":0.000566167}'

**Comment by chiragvels** [comment]
I am able to solve this 
"openhermes not found error" - by running ollama run openhermes
localhost:7777 just says {"detail":"Not Found"} - Yes It should have options to run locally or remotely. Otherwise no use of this.
localhost:6333 is running {"title":"qdrant - vector search engine","version":"1.12.3","commit":"7629faa6526aa866099b73d6c9b55aea47c2b54b"} - I think this should be 
localhost:6333/dashboard

**Comment by Shubhamsaboo** [comment]
A few things: 

OllamaEmbedder() uses OpenAI like syntax -- so it may be providing openai python package not installed error. But it's all local. 

By default OllamaEmbedder() embedder uses "OpenHermes" for embeddings -- but this could be changed by providing the model name as parameter to OllamaEmbedder(). Check this link here for proper syntax: https://docs.phidata.com/embedder/ollama

And it's all running locally. Check the demo video here: https://www.youtube.com/watch?v=jjDrHWXQOaY&t=10s

Hope I answered all your questions.
