### ISSUE TITLE
Issue in running llama3_local_rag

### ISSUE THREAD

**Issue by sathiya-mit** [Shubhamsaboo/awesome-llm-apps#4]
Getting below error.

ValueError: Error raised by inference endpoint: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x124e0a310>: Failed to establish a new connection: [Errno 61] Connection refused'))

**Comment by gth-ai** [comment]
Hi,
You must first install [ollama](https://ollama.com/) in your computer (it will act as a server).

**Comment by Shubhamsaboo** [comment]
I think the above comment would solve your problem @sathiya-mit. 

Thanks @gth-ai for jumping in and supporting the community.
