### ISSUE TITLE
Pillow==11.0.0 and streamlit==1.30.0 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by AtomAwa** [Shubhamsaboo/awesome-llm-apps#58]
Build a Multimodal AI Agent Design Team Moduel
I try pip install -r queirements.txt tips   Cannot install Pillow==11.0.0 and streamlit==1.30.0 because these package versions have conflicting dependencies

**Comment by Shubhamsaboo** [comment]
@Madhuvod can you please check this?

**Comment by Madhuvod** [comment]
hey @AtomAwa thanks for pointing it out. resolved the issue - it is indeed raising an error. changed the version of streamlit to 1.41.1 in the requirements.txt and added it to the pr @Shubhamsaboo  https://github.com/Shubhamsaboo/awesome-llm-apps/pull/59/commits/ba7478407a98d28178a95ef1da22429d3bf020ca , can merge it!

**Comment by Shubhamsaboo** [comment]
Thanks guys!
