### ISSUE TITLE
hit rate rate limit for 'chat with git' almost right away

### ISSUE THREAD

**Issue by byjlw** [Shubhamsaboo/awesome-llm-apps#7]
I got rate limited after 4 questions.
Not sure what's happening under the hood to hit the rate limit so fast but it's probably best to do this sort of thing using a local clone

RateLimitExceededException: 403 {"message": "API rate limit exceeded for user ID xxxx. If you reach out to GitHub Support for help, please include the request ID xxxxxxxx and timestamp 2024-05-13 16:51:22 UTC.", "documentation_url": "https://docs.github.com/rest/overview/rate-limits-for-the-rest-api"}

**Comment by Shubhamsaboo** [comment]
Yup, because that's an LLM heavy operation. I will soon add the local version of Chat with GitHub using Llama-3. 

Then it will be pretty much free to use it without worrying about the tokens.

**Comment by Shubhamsaboo** [comment]
Here it is: https://github.com/Shubhamsaboo/awesome-llm-apps/blob/main/chat_with_github/chat_github_llama3.py
